[package]
name = "algorithms"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
gnuplot = { version = "0.0", optional = true }

[features]
sort = []
max_subarray = []
default = ["sort", "max_subarray", "gnuplot"]

[[bin]]
name = "plot"
required-features = ["gnuplot"]
